name: test-pic
on:
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Creare un'immagine di esempio
        run: |
          sudo apt-get install imagemagick -y
          convert -size 200x100 xc:blue image.png

      - name: Salvare l'immagine come artifact
        uses: actions/upload-artifact@v3
        with:
          name: generated-image
          path: image.png

  show-image-in-summary:
    runs-on: ubuntu-latest
    needs: generate-image
    steps:
      - name: Scaricare l'immagine dall'artifact
        uses: actions/download-artifact@v3
        with:
          name: generated-image
          path: .
