name: test-pic
on:
  workflow_dispatch:

jobs:
  test-pic:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: example
        run: wget "https://avatars.githubusercontent.com/u/20147732?s=48&v=4" -O pic.png

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pic-as-artifact
          path: pic.png
