name: test-pic
on:
  workflow_dispatch:

jobs:
  test-pic:
    timeout-minutes: 180
    runs-on: ubuntu-24.04
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://github.com/karol-brejna-i/webpage-screenshot-action/blob/main/README.md
          output: example-readme.png

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://wowgaming.altervista.org/aowow/?npc=28701
          output: npc-28701.png

      - uses: karol-brejna-i/webpage-screenshot-action@v1
        with:
          url: https://google.com
          output: google.png

      - uses: actions/upload-artifact@v4
        with:
          name: webapp-screenshot
          path: ${{ github.workspace }}/*.png
          retention-days: 30
